# ---------- BUILD STAGE ----------
FROM eclipse-temurin:21-jdk-alpine AS build

WORKDIR /app
COPY . .

# Give execute permission to Maven wrapper
RUN chmod +x mvnw

# Build the application
RUN ./mvnw -B -DskipTests clean package

# ---------- RUN STAGE ----------
FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

# Copy only the built jar
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

CMD ["sh", "-c", "java -Dserver.port=${PORT:-8080} -jar app.jar"]
